blank_issues_enabled: true
contact_links:
  - name: 📖 Documentation
    url: https://github.com/ChrisMcKee1/mtech-pro-vscode-themes#readme
    about: View the README for theme descriptions and usage
  - name: 💬 Discussions
    url: https://github.com/ChrisMcKee1/mtech-pro-vscode-themes/discussions
    about: Ask questions or share ideas with the community
